version: "3.3"
services:
  node:
    image: landscapedatacommons/dl_node:1.1.6
    build:
      context: .
      dockerfile: ./app/node.Dockerfile
    container_name: node
    volumes:
      # - ./app:/usr/src
      # comment out the shared if debugging
      # the creation of live files
      - shared:/usr/src/temp
    # env file for docker compose debug
    env_file:
      - ./app/db/.env

    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 20s
      
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    

  cron:
    image: landscapedatacommons/dl_cron:1.0.1
    build:
      context: .
      dockerfile: ./cron_container/cron.Dockerfile
    container_name: cron
    volumes:
      # uncomment to have packet production happen in shared docker volume
      - shared:/usr/src/temp
      # uncomment to have packet production happen locally
      # - ./app/temp:/usr/src/app/temp
    secrets:
      - cron_mongopath
    # env_file:
    #   - .env
    
  nginx:
    image: landscapedatacommons/dl_nginx:1.0
    build:
      context: .
      dockerfile: ./nginx_container/nginx.Dockerfile
    container_name: nginx
    ports:
      - 5001:8081

  mongo:
    image: mongo:4.4.15
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    # env file for docker compose debug
    env_file:
      - .env
    volumes: 
      - mongodata:/data/db
    # config for docker stack setup

    

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    container_name: mongo-express
    volumes:
      - mongodb_config:/data/configdb

    # env file for docker compose debug
    env_file:
      - .env

secrets:
   cron_mongopath:
     external: true


volumes:
  mongodata:
  mongodb_config:
  shared:
