version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: ./app/node.Dockerfile
    container_name: node
    volumes:
      # - ./app:/usr/src
      # comment out the shared if debugging
      # the creation of live files
      - shared:/usr/src/temp
    env_file:
      - ./app/db/.env

  cron:
    build:
      context: .
      dockerfile: ./cron_container/cron.Dockerfile
    container_name: cron
    volumes:
      # uncomment to have packet production happen in shared docker volume
      - shared:/usr/src/temp
      # uncomment to have packet production happen locally
      # - ./app/temp:/usr/src/app/temp
    env_file:
      - .env
    
  nginx:
    build:
      context: .
      dockerfile: ./nginx_container/nginx.Dockerfile
    container_name: nginx
    ports:
      - $WEB_PORT:8081

  mongo:
    image: mongo:4.4.15
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOINIT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOINITPASS}
    container_name: mongo
    ports:
      - $MONGO_PORT:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    container_name: mongo-express
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGOINIT}:${MONGOINITPASS}@mongo:27017/"
      ME_CONFIG_SITE_BASEURL: '/mongo'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    volumes:
      - mongodb_config:/data/configdb
    
volumes:
  mongodata:
  mongodb_config:
  shared:
