
name: download service build


on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # skipping cicd until environment variables are figured out (sudo -E )
  push:
    branches: [ Production ]
  pull_request:
    branches: [ skip actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
    #  code checkout 
      - name: checkout code
        uses: actions/checkout@v2

    #  reading package json for version
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        with: 
          path: "./app/package.json"
        id: package-version

    ##########################################
    # keeping track of docker image on the hub 
      - name: Docker login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push 
        id: docker_build 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: landscapedatacommons/dl_node:${{ steps.package-version.outputs.version }}
  
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker service update dlservice_node \
            --image=docker.io/landscapedatacommons/dl_node:${{ steps.package-version.outputs.version }}